### ISSUE TITLE
Showing Index Out of Range When I Have Assets

### ISSUE THREAD

**Issue by hal-8999-alpha** [pieces-app/cli-agent#81]
Getting the following error when I do a fresh install and run pieces run.

Couple things: 
1. I have assets
2. I'm running 3.12.2

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jayson\.conda\envs\pieces\Scripts\pieces.exe\__main__.py", line 7, in <module>
  File "C:\Users\Jayson\.conda\envs\pieces\Lib\site-packages\pieces\app.py", line 127, in main 
    args.func(**vars(args))
  File "C:\Users\Jayson\.conda\envs\pieces\Lib\site-packages\pieces\commands\cli_loop.py", line 54, in loop
    startup()
  File "C:\Users\Jayson\.conda\envs\pieces\Lib\site-packages\pieces\commands\commands_functions.py", line 55, in startup
    current_asset = get_asset_ids(1)[0] # default current asset to the most recent
                    ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range`

**Comment by PerfectDark-J** [comment]
@BishoyHanyRaafat 

Couple things: 
1. I just searched the codebase for "identifiers" and only found one occurrence of the word: 
 
Line 48 of assets.api: 
`api_response = assets_api.assets_identifiers_snapshot()`

2. I searched all occurrences of http and I don't have any with https

Is this reference in a branch that hasn't been merged?

**Comment by BishoyHanyRaafat** [comment]
Can u show me the /assets/identifiers endpoint
