### ISSUE TITLE
Unhandled exception on almost all operations on MacOS

### ISSUE THREAD

**Issue by furious-cat** [pieces-app/cli-agent#95]
Using v 1.1.0 from brew cask on Sonoma.

All operations except version and create result in:

```
> pieces list models
Unhandled exception:
Null check operator used on a null value
#0      AssetFormats.fromJson (package:runtime_common_library/model/asset_formats.dart:84)
#1      Asset.fromJson (package:runtime_common_library/model/asset.dart:305)
#2      Asset.listFromJson (package:runtime_common_library/model/asset.dart:326)
#3      Assets.fromJson (package:runtime_common_library/model/assets.dart:76)
#4      Cacher.cache (package:pieces_cli/src/util/cacher.dart:86)
<asynchronous suspension>
#5      _initChecks (file:///Users/runner/work/pieces-cli/pieces-cli/bin/main.dart:109)
<asynchronous suspension>
#6      main (file:///Users/runner/work/pieces-cli/pieces-cli/bin/main.dart:27)
<asynchronous suspension>
```

**Comment by Bishoy-at-pieces** [comment]
That is a very old version on homebrew which is not working
We are deploying the current version and everything should work

**Comment by Bishoy-at-pieces** [comment]
Not ready on homebrew it is ready on pip

**Comment by Bishoy-at-pieces** [comment]
We can open this issue until it is updated on homebrew

**Comment by Bishoy-at-pieces** [comment]
Note still under development if any issue please report it thank you

**Comment by Bishoy-at-pieces** [comment]
Should be deployed on brew in few hours
