### ISSUE TITLE
Unable to install CLI on a Mac

### ISSUE THREAD

**Issue by IgorGanapolsky** [pieces-app/cli-agent#98]
I tried to run this command:
`pip install pieces-cli`, but received this error -
> Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_internal/cli/main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_internal/build_env.py", line 19, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_internal/cli/spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_internal/utils/logging.py", line 13, in <module>
    from pip._vendor.rich.console import (
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/rich/__init__.py", line 17, in <module>
    _IMPORT_CWD = os.path.abspath(os.getcwd())
                                  ^^^^^^^^^^^
PermissionError: [Errno 1] Operation not permitted

**Comment by Bishoy-at-pieces** [comment]
Can you please rerun it again
Pip install pieces-cli

**Comment by IgorGanapolsky** [comment]
It works now.  Thanks.
